services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_TEST_USERNAME}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - "${DB__TEST_PORT}:5432"
